config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pipeline/:name' => "pages#pipeline", as: :pipeline
  post 'payload' => 'hooks#payload'
  post 'github' => 'hooks#github'

  get 'cloud/new' => 'clouds#new', as: :new_cloud
  get 'cloud/create' => 'clouds#create', as: :create_cloud
  get 'cloud/:id' => 'clouds#cloud', as: :cloud
  get 'cloud/:id/deploy' => 'clouds#deploy', as: :deploy_cloud
  get 'cloud/:id/destroy' => 'clouds#destroy', as: :destroy_cloud

end

app/views/pages/home.html.erb
<%@clouds.each do |cloud|%>
  <div class='cloud'>
    <h3><%=cloud.name%></h3>
    <%=link_to 'View', cloud_path(id:cloud.id)%>
  </div>
<%end%>
<%i=0%>
<br><br><br>
<%=link_to 'Build New Stack', new_cloud_path, class: 'btn btn-primary', data: { confirm: 'Are you sure? This will create a new insatnce' }%>
<%count=0%>

app/views/pages/instances.html.erb
<%@resp.reservations.each do |res|%>
  <%res.instances.each do |instance|%>
    <%=instance.instance_id%><br>
    <%=instance.state.name%><br>
    <%=instance.public_dns_name%><br>
    Keypair: <%=instance.key_name%><br>
    <%=instance.instance_type%><br>
  <%end%>
<%end%>

app/views/pages/pipeline.html.erb
<h3>Cluster</h3>
<div class='stage'>
<h4><%=@cluster.cluster_name%> <small>Status: <%=@cluster.status%></small></h4>
  # of Instances: <%=@cluster.registered_container_instances_count%><br>
  Running Tasks: <%=@cluster.running_tasks_count%><br>
  Pending Tasks: <%=@cluster.pending_tasks_count%><br>
  Active Services:  <%=@cluster.active_services_count%><br>
</div>

<h3>Cloud Formation Stack</h3>
<div class='stage'>
<h4><%=@stack.stack_name%> <small>Status: <%=@stack.stack_status%></small></h4>
  <%=@stack.description%><br>
  <%=@stack.last_updated_time ? @stack.last_updated_time : @stack.creation_time%>
</div>

<h3>CodeDeploy</h3>
<div class='stage'>
<h4><%=@codedeploy.deployment_group_name%> <small>Config Group: <%=@codedeploy.deployment_config_name%></small></h4>
  EC2 Key: <%=@codedeploy.ec2_tag_filters.first.key%> | EC2 Value: <%=@codedeploy.ec2_tag_filters.first.value%>
</div>

<h3><%=@resp.pipeline_name%></h3>
<%@resp.stage_states.each do |stage|%>
  <div class='stage'>
    <h3><%=stage.stage_name%></h3>
    <%=stage.inbound_transition_state%> |<br>
    <%stage.action_states.each do |action|%>
      <%=action.action_name%> |<br>
      Rev: <%=action.current_revision%> |<br>
      <%if action.latest_execution%>
        <h4><%=action.latest_execution.status%></h4>
        <%@jobs = true if action.latest_execution.status == 'InProgress'%>
      <%end%>
      Execution: <%=action.latest_execution%> |<br>
      <%=action.entity_url%> |<br>
      <%=action.revision_url%><br>
    <%end%><br>
  </div>
<%end%>

<br><br><br><br>
<%if @jobs%>
  Jobs Pending
  <%=Job.build_spec%>
<%end%>

<br><br><br><br>
<br><br><br><br>
<br><br><br><br>