config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pipeline/:name' => "pages#pipeline", as: :pipeline
  post 'payload' => 'hooks#payload'
  post 'github' => 'hooks#github'

  get 'cloud/new' => 'clouds#new', as: :new_cloud
  get 'cloud/create' => 'clouds#create', as: :create_cloud
  get 'cloud/:id' => 'clouds#cloud', as: :cloud
  get 'cloud/:id/deploy' => 'clouds#deploy', as: :deploy_cloud
  get 'cloud/:id/destroy' => 'clouds#destroy', as: :destroy_cloud

end

app/models/cloud.rb
class Cloud < ActiveRecord::Base
  has_one :cloud_formation_stack
  has_one :code_deploy
  has_one :code_pipeline
  has_one :ecs_cluster
  has_one :instance
end

app/controllers/clouds_controller.rb
class CloudsController < ApplicationController
  before_action :get_cloud, only: [:cloud, :deploy, :destroy]

  def new
    # CodeDeploy
    cd_client = Aws::CodeDeploy::Client.new(
      region: 'us-east-1'
    )
    resp = cd_client.get_deployment_group({
      application_name: 'Demo', # required
      deployment_group_name: 'Demo', # required
    })
    @codedeploy = resp.deployment_group_info
  end

  def cloud
    # CloudFormation
    # cloudformation_name = @cloud.cloud_formation_stack.name
    # Codedeploy
    # deploy_application = @cloud.code_deploy.app_name
    # deploy_group = @cloud.code_deploy.group_name
    if @cloud.code_pipeline.present?
      # CodePipeline
      pipeline_name = @cloud.code_pipeline.name

      # Pipeline Client
      pipeline_client = Aws::CodePipeline::Client.new(
        region: 'us-east-1'
      )

      @resp = pipeline_client.get_pipeline_state({
        name: pipeline_name, # required
      })
    end

    if @cloud.ecs_cluster.present?
      # ECS Cluster
      cluster_name = @cloud.ecs_cluster.name

      # ECS Client
      ecs_client = Aws::ECS::Client.new(
        region: 'us-east-1'
      )

      clusters = ecs_client.describe_clusters({
        clusters: [cluster_name],
      })
      @cluster = clusters.clusters.first
    end

    # EC2 Instance
    if @cloud.instance.present?
      ids = @cloud.instance.ids.split(', ')
      # EC2 Client
      instance_client = Aws::EC2::Client.new(
        region: 'us-east-1'
      )
      resp = instance_client.describe_instances({
        dry_run: false,
        instance_ids: ids,
      })
      @instances = resp.reservations.first.instances
    end


    # CloudFormation
    # cf_client = Aws::CloudFormation::Client.new(
    #   region: 'us-east-1'
    # )
    # resp = cf_client.describe_stacks({
    #   stack_name: cloudformation_name,
    # })
    # @stack = resp.stacks.first

    # # CodeDeploy
    # cd_client = Aws::CodeDeploy::Client.new(
    #   region: 'us-east-1'
    # )
    # resp = cd_client.get_deployment_group({
    #   application_name: deploy_application, # required
    #   deployment_group_name: deploy_group, # required
    # })
    # @codedeploy = resp.deployment_group_info
  end

  def deploy
    pipeline = @cloud.code_pipeline
    client = Aws::CodePipeline::Client.new(
      region: 'us-east-1'
    )
    resp = client.start_pipeline_execution({
      name: pipeline.name, # required
    })
    redirect_to cloud_path(id:@cloud.id)
  end

  def create
    cloud = Cloud.create(name: params[:cloud_name])

    # ECS Cluster
    hub = params[:docker_hub]
    cluster_name = params[:cluster_name]

    # EC2 Instance
    number_of_instances = params[:number_of_instances]
    key_pair = params[:key_pair]

    # CodePipeline
    github_owner = params[:codepipeline_github_owner]
    repo = params[:codepipeline_repo]
    pipeline_name = params[:codepipeline_name]

    # ECS Cluster
    cluster = Aws::EcsCluster.new('us-east-1')
    cluster.create(cluster_name)
    # ecs_cluster(cluster_name)
    EcsCluster.create(name: params[:cluster_name], hub: params[:docker_hub], cloud_id: cloud.id)

    # EC2 Instances
    instance = Aws::Instance.new('us-east-1')
    ids = instance.create(key_pair, number_of_instances, cluster_name)
    # ids = instance(key_pair, number_of_instances, cluster_name)
    Instance.create(ids: ids, cloud_id: cloud.id)

    # CodePipeline
    pipeline = Aws::Pipeline.new('us-east-1')
    pipeline.create(pipeline_name, github_owner, repo, hub, cluster_name)
    # code_pipeline(pipeline_name, github_owner, repo, hub, cluster_name)
    CodePipeline.create(github_owner: params[:codepipeline_github_owner], name: params[:codepipeline_name],
      repo: params[:codepipeline_repo], hub: params[:docker_hub], cloud_id: cloud.id)


    # Cloud Formation
    # CloudFormationStack.create(name: params[:cloudformation_name], cloud_id: cloud.id)
    # stack_name = params[:cloudformation_name]

    # CodeDeploy
    # keyandvalue = params[:codedeploy_key]
    # deploy_config_name = params[:codedeploy_config_name]
    # deploy_application = params[:codedeploy_app_name]
    # deploy_group = params[:codedeploy_group_name]
    # CloudFormation
    # cloud_formation(stack_name, cluster_name)

    # CodeDeploy
    # code_deploy(keyandvalue, deploy_config_name, deploy_application, deploy_group)
    # CodeDeploy.create(config_name: params[:codedeploy_config_name],
    #   app_name: params[:codedeploy_app_name], group_name: params[:codedeploy_group_name],
    #   key: params[:codedeploy_key], value: params[:codedeploy_value], cloud_id: cloud.id)

    redirect_to cloud_path(id:cloud.id)
  end

  # def cloud_formation(stack_name, cluster_name)
  #   # Init cloud formation
  #   client = Aws::CloudFormation::Client.new(
  #     region: 'us-east-1'
  #   )

  #   # Create stack
  #   resp = client.create_stack({
  #     stack_name: stack_name, # required
  #     template_body: my_json(cluster_name),
  #     timeout_in_minutes: 5,
  #     capabilities: ["CAPABILITY_IAM"], # accepts CAPABILITY_IAM
  #     on_failure: "ROLLBACK", # accepts DO_NOTHING, ROLLBACK, DELETE
  #   })
  # end
  # def encode(cluster_name)
  #   text = "#!/bin/bash -ex\n
  #           echo ECS_CLUSTER="+cluster_name+" >> /etc/ecs/ecs.config\n
  #           yum install -y docker\n
  #           service docker start\n
  #           usermod -a -G docker ec2-user\n
  #           yum update -y aws-cfn-bootstrap\n
  #           yum install -y ruby\n
  #           yum install -y aws-cli\n
  #           cd /home/ec2-user\n
  #           aws s3 cp 's3://aws-codedeploy-us-east-1/latest/codedeploy-agent.noarch.rpm' .\n
  #           chmod +x ./install\n
  #           ./install auto\n"

  #   Base64.encode64(text)
  # end
  
  # def code_deploy(keyandvalue, config_name, deploy_application, deploy_group)
  #   client = Aws::CodeDeploy::Client.new(
  #     region: 'us-east-1'
  #   )
  #   # TODO - check for config
  #   # Create Config
  #   # resp = client.create_deployment_config({
  #   #   deployment_config_name: config_name, # required
  #   #   minimum_healthy_hosts: {
  #   #     value: 0,
  #   #     type: "HOST_COUNT", # accepts HOST_COUNT, FLEET_PERCENT
  #   #   },
  #   # })

  #   # TODO - check for application
  #   # # Create Applicaiton
  #   # resp = client.create_application({
  #   #   application_name: deploy_application, # required
  #   # })

  #   # Create Group
  #   resp = client.create_deployment_group({
  #     application_name: deploy_application, # required
  #     deployment_group_name: deploy_group, # required
  #     deployment_config_name: config_name,
  #     ec2_tag_filters: [
  #       {
  #         key: keyandvalue,
  #         value: keyandvalue,
  #         type: "KEY_AND_VALUE", # accepts KEY_ONLY, VALUE_ONLY, KEY_AND_VALUE
  #       },
  #     ],
  #     service_role_arn: "arn:aws:iam::360684457758:role/CodeDeploySampleStack-5iza1yvi-CodeDeployTrustRole-1FJL8II2SHASY", # required
  #   })
  # end

  def destroy
    # Cloud Formation
    # stack_name = @cloud.cloud_formation_stack.name

    # # CodeDeploy
    # keyandvalue = @cloud.code_deploy.key
    # deploy_config_name = @cloud.code_deploy.config_name
    # deploy_application = @cloud.code_deploy.app_name
    # deploy_group = @cloud.code_deploy.group_name

    # ECS Cluster
    if @cloud.ecs_cluster
      cluster = Aws::EcsCluster.new('us-east-1')
      cluster.destroy(@cloud.id)
    end

    if @cloud.instance
      instance = Aws::Instance.new('us-east-1')
      instance.destroy(@cloud.id)
    end

    

    if @cloud.code_pipeline
      pipeline = Aws::Pipeline.new('us-east-1')
      pipeline.destroy(@cloud.id)
    end


    # # CodeDeploy
    # client = Aws::CodeDeploy::Client.new(
    #   region: 'us-east-1'
    # )
    # client.delete_deployment_group({
    #   application_name: deploy_application, # required
    #   deployment_group_name: deploy_group, # required
    # })

    # Delete Application
    # resp = client.delete_deployment_group({
    #   application_name: "DemoApp", # required
    #   deployment_group_name: "MyNewGroup", # required
    # })

    # Delete Config
    # resp = client.delete_deployment_config({
    #   deployment_config_name: config_name, # required
    # })

    # @cloud.code_deploy.destroy

    # # CloudFormation
    # cloud_formation(stack_name, cluster_name)
    # client = Aws::CloudFormation::Client.new(
    #   region: 'us-east-1'
    # )
    # resp = client.delete_stack({
    #   stack_name: stack_name, # required
    # })
    # @cloud.cloud_formation_stack.destroy

    @cloud.destroy

    redirect_to root_path, notice: 'Destroyed'
  end

  private

  def get_cloud
    @cloud = Cloud.find(params[:id])
  end
end

app/views/clouds/cloud.html.erb
<%if @cloud.ecs_cluster%>
  <h3>Cluster</h3>
  <div class='stage'>
  <h4><%=@cluster.cluster_name%> <small>Status: <%=@cluster.status%></small></h4>
    # of Instances: <%=@cluster.registered_container_instances_count%><br>
    Tasks
    <div class='badging'>
      Pending: <%=@cluster.pending_tasks_count%><br>
    </div>
    <div class='badging'>
      Running: <%=@cluster.running_tasks_count%>
    </div>
    Active Services:  <%=@cluster.active_services_count%><br>
    ARN: <%=@cluster.cluster_arn%><br>
  </div>
<%end%>

<%if @cloud.instance%>
  <h4>Instances <small><%=@instances.count%></small></h4>
  <div class='stage'>
    <%@instances.each do |instance|%>
      <div class='instance'>
        <%=instance.state.name%><br>
        <%=instance.instance_id%><br>
        <%=instance.public_dns_name%><br>
        <%=instance.instance_type%><br>
        <%=instance.security_groups.map{|s| s.group_name}%><br>
        <%=instance.iam_instance_profile.arn%><br>
      </div>
    <%end%>
  </div>
<%end%>

<%if @cloud.code_pipeline%>
  <h3><%=@resp.pipeline_name%></h3>
  <%=link_to 'Deploy', deploy_cloud_path, class: 'btn btn-success', data: {confirm: "Are you sure you want to deploy?"}%>
  <%@resp.stage_states.each do |stage|%>
    <%@status = stage.action_states.last.latest_execution ? stage.action_states.last.latest_execution.status : 'Not ran'%>
    <div class='stage <%=@jobs ? 'Waiting' : @status%>'>
      <h3><%=stage.stage_name%></h3>
      <%=stage.inbound_transition_state%> |<br>
      <%stage.action_states.each do |action|%>
        <%=action.action_name%> |<br>
        Rev: <%=action.current_revision%> |<br>
        <%if @jobs%>
          <h4>Waiting</h4>
        <%else%>
          <%if action.latest_execution%>
            <h4><%=action.latest_execution.status%></h4>
            <%@jobs = true if action.latest_execution.status == 'InProgress'%>
            <%@job_name ||= action.action_name if action.latest_execution.status == 'InProgress'%>
          <%end%>
        <%end%>
        Execution: <%=action.latest_execution%> |<br>
      <%end%><br>
    </div>
  <%end%>
<%end%>

<br><br><br><br>
<%if @jobs%>
  <%=@job_name%> Pending
<%end%>

<br><br><br><br>
<%=link_to 'Destroy', destroy_cloud_path(id: @cloud.id), class: 'btn btn-danger', data: {confirm: 'Are you sure?'}%>
<br><br><br><br>
<br><br><br><br>

app/views/clouds/new.html.erb
<%=form_tag create_cloud_path, method: :get do%>
  <div class='form-section'>
    <div class='form-image' style='height:75px'><i class="fa fa-cloud fa-5x" style='color:lightblue'></i></div>
    <div class='form-forms'>
      Cloud Name:
      <%= text_field_tag :cloud_name, '', class: 'form-control' %>
    </div>
  </div>

  <div class='form-section'>
    <div class='form-image'><%=image_tag '/ecs.jpg'%></div>
    <div class='form-forms'>
    Cluster Name:
    <%= text_field_tag :cluster_name, '', class: 'form-control' %>
    Docker Hub:
    <%= text_field_tag :docker_hub, 'davidrichey/baseruby', class: 'form-control' %>
    </div>
  </div>

  <div class='form-section'>
    <div class='form-image'><%=image_tag '/ec2.jpg'%></div>
    <div class='form-forms'>
    EC2 Instance Keypair:
    <%= text_field_tag :key_pair, 'davidrichey', class: 'form-control' %>
    Number Of Instances:
    <%= number_field_tag :number_of_instances, '1', class: 'form-control' %>
    </div>
  </div>

  <div class='form-section'>
    <div class='form-image'><%=image_tag '/codepipeline.jpg'%></div>
    <div class='form-forms'>
    Pipeline Name
    <%= text_field_tag :codepipeline_name, '', class: 'form-control' %>
    CodePipeline GitHub Owner
    <%= text_field_tag :codepipeline_github_owner, 'david-richey', class: 'form-control' %>
    CodePipeline GitHub Repo
    <%= text_field_tag :codepipeline_repo, 'demoapp', class: 'form-control' %>
    </div>
  </div>

<h3>CodeDeploy</h3>
<div class='stage'>
<h4><%=@codedeploy.deployment_group_name%> <small>Config Group: <%=@codedeploy.deployment_config_name%></small></h4>
  EC2 Key: <%=@codedeploy.ec2_tag_filters.first.key%> | EC2 Value: <%=@codedeploy.ec2_tag_filters.first.value%>
</div>

  <br><br>
  <%=submit_tag 'Create', class: 'btn btn-primary btn-lg'%>
<%end%>